# _____  ___        __       ___      ___   _______  ___________   __       _______   ________  
#(\"   \|"  \      /""\     |"  \    /"  | /"     "|("     _   ") /""\     /" _   "| /"       ) 
#|.\\   \    |    /    \     \   \  //   |(: ______) )__/  \\__/ /    \   (: ( \___)(:   \___/  
#|: \.   \\  |   /' /\  \    /\\  \/.    | \/    |      \\_ /   /' /\  \   \/ \      \___  \    
#|.  \    \. |  //  __'  \  |: \.        | // ___)_     |.  |  //  __'  \  //  \ ___  __/  \\   
#|    \    \ | /   /  \\  \ |.  \    /:  |(:      "|    \:  | /   /  \\  \(:   _(  _|/" \   :)  
# \___|\____\)(___/    \___)|___|\__/|___| \_______)     \__|(___/    \___)\_______)(_______/ 
#
#                     Created by Acquized, maintained by LimeGlass
#
# Configuration Version.
version: "2.0.0"

# Edit all plugin messages here.
messages:
    # Messages prefix.
    prefix: "&a> &7"